### ISSUE TITLE
npm version

### ISSUE THREAD

**Issue by George9000** [brucala/Deneb.jl#3]
While trying out Deneb, the following warning was printed:
```
npm notice
npm notice New major version of npm available! 8.5.5 -> 9.8.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.8.0
npm notice Run npm install -g npm@9.8.0 to update!
npm notice
```

I don't have `npm` installed. Is this an artifact that Deneb installs? If so, should the version be updated?

**Comment by brucala** [comment]
It is an artifact that Deneb.jl installs (`NodeJS_16_jll`). If I'm correct probably you will see similar outputs from nodejs the first time you generate plots and some nodejs dependencies get installed. Normally those messages should disappear later. However, the message that you are reporting is different than what I'm used to observe. I'll have a look and bump dependencies if necessary.

**Comment by brucala** [comment]
Fixed by https://github.com/brucala/Deneb.jl/pull/4
